src/App.tsx
src/components/ContactTitleBox.tsx
src/components/LongLeftMargin.tsx
src/components/LongRightMargin.tsx
src/pages/About.tsx
src/pages/Contact.tsx
src/theme/styles.ts

Added contact page and ContactTitleBox component. Closes #45.

Add Contact Us title component

---

src/components/Header.tsx

This is a temporary fix until we implement the mobile header. I also improved the green underline selection indicator positioning because I noticed it was a little off.

Improved header font sizing on mobile

---

src/components/Footer.tsx
src/components/FooterDesktop.tsx
src/components/FooterMobile.tsx

Added mobile footer. Closes #58.

Add mobile footer

---

src/pages/Home.tsx
yarn.lock

re-created yarn lock file and removed duplicate import in Home.tsx

fix yarn lock file

---

src/components/careers/desktop/CareersTitleBox.tsx
src/components/careers/desktop/PerkBox.tsx
src/pages/Careers.tsx

Added CareersTitleBox, make PerkBox responsive, and updated Careers page. Closes #66.

Add desktop Careers page Title Box Component

---

public/imgs/check-mark-icon.svg
public/imgs/globe-icon.svg
public/imgs/logos/github-logo-icon.svg
src/Utils/networkUtils.ts
src/components/careers/desktop/ChipSmall.tsx
src/components/careers/desktop/ProfileSummary.tsx
src/components/careers/desktop/profilePopUp/ChipLarge.tsx
src/components/careers/desktop/profilePopUp/ClosePopUpButton.tsx
src/components/careers/desktop/profilePopUp/HireMeButton.tsx
src/components/careers/desktop/profilePopUp/NameBioContainer.tsx
src/components/careers/desktop/profilePopUp/PortfolioLinkContainer.tsx
src/components/careers/desktop/profilePopUp/ProfileFull.tsx
src/components/careers/desktop/profilePopUp/ProfilePhoto.tsx
src/components/careers/desktop/profilePopUp/ProfileSectionTitle.tsx
src/components/careers/desktop/profilePopUp/SpecializationsContainer.tsx
src/components/careers/desktop/profilePopUp/TechnologiesContainer.tsx
src/pages/Careers.tsx

Added desktop dOrg member profile pop-up component. Closes #82.

Add desktop dOrg member profile pop-up component

---

package.json
src/components/careers/desktop/GreenDotsRectangle.tsx
src/components/careers/desktop/TestimonialSection.tsx
src/components/careers/desktop/TestimonialsCarousel.tsx
src/components/careers/desktop/TestomonialItem.tsx
src/constants/testimonials.ts
src/pages/Careers.tsx
yarn.lock

Added desktop [Careers page](https://app.zeplin.io/project/5fc8757e071b5908d4857503/screen/5fcb0874d3eb954107c861ff) testimonials carousel and background. Closes #69. Closes #81.

Add desktop Careers page Testimonials component

---

public/imgs/check-circle.svg
src/components/careers/desktop/portfolio_section/ProfileSummary.tsx
src/components/home/desktop/ClientContainer.tsx
src/components/home/desktop/ClientItem.tsx
src/components/home/desktop/ProjectHover/BulletsBox.tsx
src/components/home/desktop/ProjectHover/HoverContentBox.tsx
src/components/home/desktop/ProjectHover/HoverFooter.tsx
src/components/home/desktop/ProjectHover/HoverHeader.tsx
src/components/home/desktop/ProjectHover/HoverMarginLeft.tsx
src/components/home/desktop/ProjectHover/HoverMarginRight.tsx
src/components/home/desktop/ProjectHover/ProjectHoverLeft.tsx
src/components/home/desktop/ProjectHover/ProjectHoverRight.tsx
src/constants/clients.ts
src/constants/communities.ts
src/constants/companies.ts
src/pages/Home.tsx

Added desktop Home page project display component. Closes #72.
I set up code structure to add images/graphics to the views, but am leaving creation of those graphics for issue #94.

Add desktop Home page project display component

---

src/components/Footer.tsx
src/constants/communities.ts
src/constants/companies.ts

I tried to add brand colors for companies and daos on the home page, in relation to issue #93. The result is alright but not great so I'm not closing the issue. Hopefully we can get more eyes on this later on.

Add highlight colors for companies and communities

---

src/components/CookieConsentPrompt.tsx
src/components/home/mobile/ClientItemMobile.tsx
src/components/home/mobile/ClientTabsMobile.tsx

fixed mobile home page responsiveness issues

---

src/Utils/hooks.tsx
src/components/CustomScrollbar.tsx
src/components/RightMargin.tsx
src/components/about/desktop/CloseBox.tsx
src/components/about/desktop/PressBox.tsx
src/components/about/mobile/AboutTitleBoxMobile.tsx
src/components/about/mobile/CloseBoxMobile.tsx
src/components/about/mobile/PitchTitleBoxMobile.tsx
src/components/about/mobile/PressBoxMobile.tsx
src/components/careers/desktop/ActivationPromptBox.tsx
src/components/careers/desktop/CareersTitleBox.tsx
src/components/careers/mobile/ActivationPromptBoxMobile.tsx
src/components/careers/mobile/CareersTitleBoxMobile.tsx
src/components/contact/desktop/ContactForm.tsx
src/components/contact/mobile/ContactFormMobile.tsx
src/components/contact/mobile/ContactTitleBoxMobile.tsx
src/components/home/desktop/ClientContainer.tsx
src/components/home/desktop/ClientItem.tsx
src/components/home/desktop/ProjectHover/HoverContentBox.tsx
src/components/home/desktop/ProjectHover/ProjectHoverRight.tsx
src/components/home/mobile/ClientContainerMobile.tsx
src/pages/About.tsx
src/pages/Home.tsx
src/theme/styles.ts

*When a project becomes "sticky", it'd be great to make it not sticky when you click off of it, instead of forcing the user to click it again.
*The front-page footer is duplicated in the pop-over, leading to the viewer being able to see the bottom-most footer, and pop-over footer at the same time
*The scrollbar for the companies is a really great touch! It's a bit hard to see what it is though because it's so dark. Maybe using a light green color to match the radial circle in the bottom right?
*The horizontal bars on the right are amazing to click on! They're a bit small and hard to click on though. Maybe we can make the "hit box" or clickable area bigger without making the visual bar itself bigger so it's easier to click them
*Animate all concentric ring graphics to have sonar effects …

Misc feedback

---

src/components/FadeInOutAnimation.tsx
src/components/about/desktop/StatBox.tsx
src/components/about/mobile/StatBoxMobile.tsx
src/components/home/desktop/HomeTitleBox.tsx
src/components/home/desktop/ProjectHover/ProjectHoverLeft.tsx
src/constants/stats.ts

animate stats on About page

---

src/App.tsx
src/components/HeaderDesktop.tsx
src/components/NavHoverContext.tsx
src/components/RightMargin.tsx
src/constants/stats.ts

highlight navigation item in header when panning over corresponding right margin accent

---

src/components/home/desktop/ClientContainer.tsx
src/components/home/desktop/ClientItem.tsx
src/components/home/desktop/ProjectHover/HoverContentBox.tsx
src/components/home/mobile/ClientItemMobile.tsx
src/pages/Contact.tsx

rework of hover/sticky behavior on home page

---

src/components/about/desktop/ClientQuoteCarousel.tsx
src/components/about/desktop/CloseBox.tsx
src/components/about/mobile/ClientQuoteCarouselMobile.tsx
src/components/about/mobile/CloseBoxMobile.tsx
src/components/careers/desktop/testimonial_section/BuilderTestimonialCarousel.tsx
src/components/careers/desktop/testimonial_section/TestimonialSection.tsx
src/components/contact/desktop/ContactForm.tsx
src/components/contact/desktop/ContactTitleBox.tsx
src/constants/contactForm.ts
src/constants/quotes.ts
src/constants/stats.ts
src/pages/About.tsx
src/pages/Contact.tsx

* Added carousel for client quotes at bottom of about page
* fixed layout bug on contact page
* fixed sonar animation bug on about page
* Changed "funding raised" stat to "on-chain revenue"
Closes #139. Closes #142. Closes #143. Closes #144.

Added carousel for client quotes on About page

---

package.json
src/components/CustomScrollbar.tsx
src/components/careers/desktop/portfolio_section/ProfileWheel.tsx
src/constants/communities.ts
src/constants/companies.ts
src/constants/quotes.ts
src/constants/routes.ts
src/constants/stats.ts
src/pages/About.tsx
src/pages/Careers.tsx
src/utils/statUtils.ts

Implemented new carousel that can be dragged to scroll. The new carousel is only implemented for desktop right now. A mobile implementation will come in the future. 
Also alphabetized companies and communities on home page, made small changes to copy as requested, and changed builder interest link so it directs to builder interest form.
Created new issue #151 for the mobile implementation of new carousel.
Closes #145. Closes #148

Builder profile carousel rework

---

src/components/home/mobile/ClientItemMobile.tsx

Fixed external links on mobile home page accordions

---

src/components/careers/desktop/portfolio_section/ProfileWheel.tsx

Closes #156.
The momentum decay rate can be adjusted by request.

add momentum to drag-scroll effect on builder carousel

---

src/components/FooterDesktop.tsx
src/components/FooterMobile.tsx
src/components/careers/desktop/portfolio_section/ProfileWheel.tsx
src/components/careers/mobile/portfolio_section/ProfileWheelMobile.tsx
src/components/contact/desktop/ContactTitleBox.tsx
src/components/contact/mobile/ContactTitleBoxMobile.tsx
src/constants/routes.ts
src/pages/Careers.tsx
src/pages/Contact.tsx

Make builders carousel dragable (mobile) and "Calls to Action" design changes

---

public/imgs/circled-arrow-icon.svg
src/components/ScrollContainer.tsx
src/components/about/desktop/PitchBox.tsx
src/components/about/mobile/PitchBoxMobile.tsx
src/components/careers/desktop/ChipSmall.tsx
src/components/careers/desktop/PerkBox.tsx
src/components/careers/mobile/ChipSmallMobile.tsx
src/components/careers/mobile/PerkBoxMobile.tsx
src/components/contact/desktop/ContactForm.tsx
src/components/contact/desktop/ContactTitleBox.tsx
src/components/contact/mobile/ContactFormMobile.tsx
src/theme/styles.ts
src/utils/colorUtils.ts

added cropped svg for contact form submit button

---

src/components/careers/desktop/portfolio_section/ProfileSummary.tsx

All images in the builder slide show should now crop to circles. I also cropped few builder profile image files and added new url's to contacts in hubspot.

adjusted builder image fit

---

src/components/CookieConsentPrompt.tsx
src/components/Footer.tsx
src/components/Header.tsx
src/components/LeftMargin.tsx
src/components/RightMargin.tsx
src/components/ScrollContainer.tsx
src/components/home/desktop/ProjectHover/ProjectGraphic.tsx
src/pages/About.tsx
src/pages/Careers.tsx
src/pages/Contact.tsx
src/pages/Home.tsx

This should be an improvement for Detect desktop vs mobile #167.

Reduced screen width threshold for transition to mobile version of site

---

src/components/CookieConsentPrompt.tsx
src/components/Footer.tsx
src/components/Header.tsx
src/components/LeftMargin.tsx
src/components/RightMargin.tsx
src/components/ScrollContainer.tsx
src/components/home/desktop/ProjectHover/ProjectGraphic.tsx
src/pages/About.tsx
src/pages/Careers.tsx
src/pages/Contact.tsx
src/pages/Home.tsx
src/theme/index.ts
src/utils/hooks.tsx

Added device detection based on user agent, to use in combination with screen width, and further lowered screen width threshold for mobile device detection. Closes #167.

improve device detection

---

src/server/server.js

Bug fix: Direct navigation to sub routes returns 404

---

netlify.toml
src/App.tsx
src/serverless/getMembers.js
src/utils/network.ts

set up serverless back end and netlify config

serverless backend

---

src/constants/openings.tsx
src/constants/pitches.ts
src/constants/testimonials.ts
src/pages/Home.tsx

various copy changes

---

src/constants/communities.ts

Reverts dOrgTech/landing-page-v2#208

Revert "Update communities.ts"

---

package.json
src/components/about/desktop/StatBox.tsx
src/serverless/submitContactForm.js
src/utils/network.ts
tsconfig.json
yarn.lock

Closes #218.
Confirmed to work in netlify deploy preview

replace the backend of dOrg's contact form to use airtable API

---

src/constants/routes.ts

update link to airtable

---

src/constants/openings.tsx

Just a quick small grammar fix in the job openings for designers.

fixed grammar with design role in openings

---

src/components/FooterDesktop.tsx

Added handbook link to desktop footer, as described in issue #250.

Add more prominent link to Builder Handbook

---

src/components/HeaderDesktop.tsx
src/components/MobileMenu.tsx
src/components/RightMargin.tsx
src/constants/routes.ts
src/pages/Contact.tsx

Add "Blog" page to website with Substack

---

src/components/FooterDesktop.tsx
src/components/FooterMobile.tsx

Updates footer based on issue #269

Updates footer

---

src/components/HeaderDesktop.tsx

Resolves issues regarding new tab/empty pages mentioned in #266

Opens header links in new tabs

---

src/components/MobileMenu.tsx
src/components/RightMargin.tsx
src/components/home/mobile/HomeTItleBoxMobile.tsx

Resolves the following bugs:
#275 
#276 
#277

Brand update bug sweep

---

package.json
src/App.tsx
src/components/CookieConsentPrompt.tsx
src/components/FooterDesktop.tsx
src/components/FooterMobile.tsx
src/components/Markdown.tsx
src/components/about/desktop/CloseBox.tsx
src/components/about/desktop/CloseButton.tsx
src/components/about/desktop/PressBox.tsx
src/components/about/mobile/CloseBoxMobile.tsx
src/components/about/mobile/PressBoxMobile.tsx
src/components/careers/desktop/profile_popup/ProfileFull.tsx
src/components/careers/mobile/profile_popup/ProfileFullMobile.tsx
src/constants/privacyPolicy.ts
src/constants/routes.ts
src/pages/About.tsx
src/pages/PrivacyPolicy.tsx
src/theme/index.ts
yarn.lock

Completed: 
- Create Private Policy UI
- Add Privacy Policy button at footer 
- Integrate private policy document as markdown
UI:

Create Private Policy UI

---

src/App.css
src/App.tsx
src/components/CookiesConsent.tsx
src/components/Markdown.tsx
src/constants/privacyPolicy.ts

Add cookies consent alert
